### PR TITLE
added support for changing alpha value and changing corner radius of the popup

### PR DESCRIPTION
**Pull request by h4rz**
- Added support to change the transparency of popup background color
- Added support to change the corner radius of popup

### CODE REVIEW

**Comment by sopharasum** [comment]
>     * Added support to change the transparency of popup background color
> 
>     * Added support to change the corner radius of popup

Thank you for your update code. I am trying to set the popupAlphaValue = 255 but the reaction view background still Color.WHITE. How to make it transparent?

**Comment by h4rz** [comment]
@sopharasum, 

Alpha value's range is from 0 to 255 where 

0 - 100% Transparency
255 - 0%  Transparency

As you had assigned 255, it won't be transparent, try changing the values below 255 and above 0 and you would get the idea.

**Comment by sopharasum** [comment]
> @sopharasum,
> 
> Alpha value's range is from 0 to 255 where
> 
> 0 - 100% Transparency
> 255 - 0% Transparency
> 
> As you had assigned 255, it won't be transparent, try changing the values below 255 and above 0 and you would get the idea.

Thank you so much.
However, are you planning to add on the reaction item showing up animation similar to this repository https://github.com/ngohado/Facebook-Reaction ?

**Comment by h4rz** [comment]
> > @sopharasum,
> > 
> > Alpha value's range is from 0 to 255 where
> > 
> > 0 - 100% Transparency
> > 255 - 0% Transparency
> > 
> > As you had assigned 255, it won't be transparent, try changing the values below 255 and above 0 and you would get the idea.
> 
> Thank you so much.
> However, are you planning to add on the reaction item showing up animation similar to this repository https://github.com/ngohado/Facebook-Reaction ?

Not as of now.

**Review by pgreze — APPROVED** [review]
Thanks for this helpful PR!
I'm planning to slightly change those attributes to be more generic but it's good enough to be merged 👍

**Comment by pgreze** [comment]
@h4rz @sopharasum feel free to use those 2 attributes with the version 1.3 that I just published: https://github.com/pgreze/android-reactions/releases/tag/v1.3

**Comment by h4rz** [comment]
@pgreze, Thank you for open-sourcing this useful library and also for improving the code, I got to learn something new😄.

**Pull request merged**
